# See http://pre-commit.com for more information
# See http://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        exclude: (cli\.rst|\.md|\.csv)$
      - id: end-of-file-fixer
        exclude: (cli\.rst|\.md|\.csv)$
      - id: check-ast
      - id: check-added-large-files
        args: ["--maxkb=200"]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: (\.bat|\.csv)$

  - repo: https://github.com/PyCQA/isort.git
    rev: "5.12.0"
    hooks:
      - id: isort
        exclude: (ksconf/ext/)

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.6
    hooks:
      - id: autopep8
        exclude: (ksconf/ext/)

  - repo: https://github.com/pycqa/flake8
    rev: "6.1.0"
    hooks:
      - id: flake8
        args:
          - --ignore
          - E741
          - --per-file-ignores=ksconf/setup_entrypoints.py:E241
        exclude: '(ksconf/_version\.py|tests/test_.*\.py)'

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.29.0
    hooks:
      - id: yamllint

  - repo: local
    hooks:
      - id: do-not-commit
        name: Block commits with invalid lines
        entry: ^(from build\.lib|import build\.)
        language: pygrep
        types: [python]

      - id: ksconf-unittest
        name: Run all unit tests for ksconf
        language: script
        entry: run_tests.py
        types: [python]
        pass_filenames: false

  # Way too much noise.... (or I just have bad code, either way it's too much)
  # - repo: https://github.com/pylint-dev/pylint
  #   rev: v3.0.1
  #   hooks:
  #     - id: pylint

  # - repo: https://github.com/jorisroovers/gitlint
  #   rev: master
  #   hooks:
  #     - id: gitlint

  # Yup this one is too busy too.  I attacked *some* of these, but there were still 270+ errors remaining to address (and some of these are like wack-a-mole, a small "fix" breaks something else.)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.6.0
  #   hooks:
  #     - id: mypy
  #       args:
  #         - '--explicit-package-bases'
  #       exclude: '(plugins/.*|splunk_app/.*)'
  #       additional_dependencies:
  #         - argcomplete
  #         - importlib-metadata
  #         - jinja2
  #         - lxml
  #         - pluggy
  #         - pyyaml
  #         - splunk-sdk
