---
language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.4'
  - os: linux
    python: '3.5'
    env: EXTRA_PKGS="argcomplete"
  - os: linux
    python: '3.6'
    env: BUILD_SDIST=true
  - os: linux
    # Travis Python 3.7 support https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
    python: '3.7'
    dist: xenial
    sudo: true
  - os: linux
    python: '3.8'
    dist: xenial
    sudo: true
  - os: linux
    python: '3.9'
    dist: xenial
    sudo: true
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.17
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.7.5
  - os: linux
    python: 'pypy3'
    dist: bionic
    sudo: true

# command to install dependencies

install:
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
        if [ ! -e "$HOME/.pyenv/.git" ]; then
            if [ -e "$HOME/.pyenv" ]; then
                rm -rf ~/.pyenv
            fi
            git clone https://github.com/pyenv/pyenv.git ~/.pyenv --depth 10
        else
            (cd ~/.pyenv; git pull)
        fi
        PYENV_ROOT="$HOME/.pyenv"
        PATH="$PYENV_ROOT/bin:$PATH"
        hash -r
        eval "$(pyenv init -)"
        hash -r
        pyenv install --list
        pyenv install -s $PYENV_VERSION
        pyenv rehash
        pip install wheel
        # Since pyenv can be cached across OSX builds, uninstall first for a fresh build
        if pip show kintyre-splunk-conf; then pip uninstall -y kintyre-splunk-conf; fi
    fi
  - pip install $EXTRA_PKGS -r requirements-ci.txt
  - pip install .
  - echo "Build $TRAVIS_BUILD_NUMBER BRANCH=$TRAVIS_BRANCH TAG=$TRAVIS_TAG"
  - pip list --format=columns
# command to run tests
script:
  - |
    if [[ $BUILD_SDIST == "true" && $TRAVIS_BRANCH =~ ^v.* ]]; then export DO_RELEASE=True; fi
    echo DO_RELEASE=$DO_RELEASE
  - ksconf --version
  - coverage run -m unittest discover -s tests
after_success:
  - '[[ $BUILD_SDIST == "true" ]] && coverage run -a -m make_cli_docs'
  - codecov
  - coveralls
  - '[[ $BUILD_SDIST == "true" ]] && python -m pip install -r requirements-doc.txt && KSCONF_DEBUG=1 python splunk_app/build.py -vv'
  - '[[ $BUILD_SDIST == "true" ]] && ls -lsh zdist'
deploy:
  - provider: releases
    api_key:
      secure: 0EyoBqjUj6AZct5sRmHhjuD8E0d0gYuTu3MUUIR/TM69L3AITSrrS1n6AO/It9G5hn03dekejHfecAbhZfhWeX2M/7q9Yv7Rwj0otOsoNpc/wg85g8GOKwoAMMhE1JsYrYkrQ8bTt0N9uojxpDnMKhtE4K1K9E6c9Mc/+B87/GW/lK3+pOap5fisPT6Q76pfZsPd/mP62hazIwBp4arsTygStqMmRh0NatOMOKHch2+gnMAT7gpxCVR1wRv5f+r2hNJCuJstgmHEks5Wuqi4GDVCqpUqYCga3AUE7SNuSfkpNupeb46HG8ITZ6cOlKnrf/7TNpDmtDCH6IZn37ULQDT9ILXnGu0oKFaVfDpAVJBcPK1mGp8wCicfJHarOeVwunAFiIH8BnykeqsFw/743bxZFp8FVjo3nbo42PcFt0oJQ2gweuNT03r62DgRA1ujblgDwac8jxnaqkoCQJe+hS8OqCj4V+npNjewhJWb6b+QFqHJfaoKJXStoNAZF+eIX0wqG5xoUM5MZlkg3D5LyvDiMTYYpw4i4qq0WcizwVJrmci9W88sHn9GlWhv+sHpb9fGfnl1PvikNEveSFlsa7TfJYPGxOOblOYLa+Us2IkfuCQn+c0QbddOCywuPijERaiYo1FzAdHjjsVhDQSpjCvL9bVQfnUiYwoIlSt6wUM=
    file: zdist/ksconf-*
    file_glob: true
    skip_cleanup: true
    on:
      all_branches: true
      condition: $DO_RELEASE = True
  - provider: pypi
    user: __token__
    password:
      secure: 1gyPI3Mc+DUInpLswll08xSQkoG00bKh96JvKdyskKl4vLGR83Frr6oKdYIyZxHoPE5o43A+VKA1CaXmeru6F/eMFqDT6O0QYuqUEo6BxnTX3RMeHEJExL2NZ2KmN9KvB0THBCg8GHXXSdAceCHm2LKJOszNpF1ajSb7ap92HMwBfJ22RKgstQ/LER7jmscfmfZ0AbOK7gBWiMW2tWEw+XuxqR6w/Tg5o6K5uHDNQNQTZTTvsjg0onnwjyFgOR5+sywypiHhlR02PCdCJWWTkVo++AE17sNi5y3PPDtvPSLOePL3e4lAOWodQEBm9b2aUUinvS/886vL7QIzhLmsA0U24AE6ym+4jK/YhhQXx9TF9CNKoU28qmVfhv3i/iiQDmjeJqeI8YWH+DoMk6g8+l2q69WNWWv+wNLgMjphaanstFvzWMIVj5N6RzKfhttZWJC54XdDV0FukxoBNMwe5lndTDJAP6Qbit7+0RKhW3upBagYEuCN+5o0RkH+cR6lgASMyUmVTCrbwMWaA30egIUOnf3bJPyKZC1dk655DWWVcA8m5ubLiqm90jxNd62lFkeed5zb/HpVNgNOcifQD0zc2GUlNswXDeQyHzzyMfPyOsX/k0BkgkfIQM9Gssoer/uUlzDXMruA0OEJltBAYnCGGCzz4sJubMEPr0Mu9w4=
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      all_branches: true
      condition: $DO_RELEASE = True

notifications:
  email:
    - lowell@kintyre.co
