---
language: python
python:
#  - "2.6"
  - "2.7"
#  - "3.4"
#  - "3.5"
#  - "3.6"
  # PyPy versions
#  - "pypy2.7"
#  - "pypy3.5"
cache: pip
# command to install dependencies
install:
  - pip install coverage
  - pip install coveralls
  - pip install codecov
  - pip install .
  - echo "Build $TRAVIS_BUILD_NUMBER"
#  - pip install -r requirements.txt
# command to run tests
#script: nosetests --with-coverage
script: coverage run -m unittest discover -s tests
after_success:
  - coveralls
  - codecov
  - ./make_zipapp
deploy:
  - provider: releases
    api_key:
      secure: j34Qukrg/cDpCceiOpiUaWeQYElKkplzSUmz49yh7DLOMHv8DAygNIW1p7wKYehdHAEJHZYZDxvv/9vKi0Bbfad0182SOci46szs62Ce71uFJW/O2rAZD8c9QNKkntXfyhIn5G6H6Dm0kBb6sbrOzPJX3zzH2hs8ssj/WgjjmqeUeVoa5u7HD3GFyGkuH3yfB4jFT31Ov7o9/PfdI7SYyaHg7XhwCWdMYojFmQYCO34hpZ6jY1pkNAUEolBuN66WBQq1Azw6SSQelXFrxWQJmMkTstrfUNan96fp8il2dAvAbcG5tomtmTxmN6UHEWInbbfJn1qq2HWUmfAhV/I+WN+8W6DoYzgdl+w4zyF8mWmrPo6diB+Ejyui8Z26v4y6SILWPPDCPXtBuSOpxRDs5bfcKP62gGu7t3Hgbw9hdbrXYVJ7sXLLILjWHghQzmTtl79BUAvSdC8mDnEiqIkbxC3Lr5wfOTLhjR5zOLY7aSHoL3yEIgmof2M3NfDt7G2ERnuSwJcchLU4C42K7SysvKjmFMMLszTVm+Jn3MsRllpvZ8/DWAFxXbN9yC0zGlxVoVJRPSjBCb1h5thAOZSt7GZosFNO4bU/YCcRLl1wUBVqpW9RDtJ6vwB5kMBed8F9K3MfAlfihrAXy+ssCusVLRZEdEaMjBJtrrcdLMhAoqE=
    file: build/ksconf-*-standalone
    file_glob: true
    skip_cleanup: true
    on:
      #repo: Kintyre/ksconf
      branch: master
  - provider: pypi
    user: lowellalleman
    password:
      secure: OqhsEKwmMHB26imHCH23UXINk0VEkeMR7uJRKvj90zz4c34VvPE5VJoYTOERMIEoNMBGr9VN1O216CJDAeykswxQG0CxsbTeIOVHB7avAQaodvWgosQDyyrwAypWtLsBu/LZdXWZ0j09CYB+DiG2zKBOdtER+YEqRSIMDFXRmWKfPvkOHkhh7v4bSjjs/w6HvV9FLgXnz1y7YxVwLmRHku8NWiqBq1q09b0gezBgOll7QhKFXMJLLtsy7V1JWV42e/B812RORiW+pnyZqLzDG6qoUd+W0aJMGUpMetm8dcgp70Teyq0jLSPVZ7BtuzudL8mimxONFr7QHDWwv2gsMKVg3xvfOJ1FvDsugGXTmbu3WtSeZEaXLaLo4xiyC5GLOGsPxZPPqpsE5K7UW14HQlCWPOYWD161fxW6stbDeIvxJOVn4aYUZFWr6jypJW2SYK1xCjSB8r8FSpJCCz1/3d5j9jFOJGf8eY9dDDkSUxWWjPHjbHjI5bWIC5k+sxXLmURA4Ne5gl4QSynX1TQFsU3AiSul93Ds6SSXSQJbSp0kwFwHPDju/g4RJB9rcH0EpJ0aTzuavvTIPLLCXO1HI8c/6uL5nWWUN6zwXjLsGrLY0Pb6VTxH/qiQPYJduWSXOXV9R2a0mGr8Jc4dCTQBeUCGGqEwMRnn3Iknx7JF0AE=
    distributions: "sdist bdist_wheel"
    skip_cleanup: true
    on:
      tags: true
      # For testing only...
      #all_branches: true
      branch: master
notifications:
  email:
    - lowell@kintyre.co
