---

build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37"
    - PYTHON: "C:\\Python37-x64"

# scripts that are called at very beginning, before repo cloning
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  # Git command run locally during testing with throw-away repos; values don't matter.
  - git config --global user.email "automation@kintyre.co"
  - git config --global user.name "App Veyor"

install:
  - echo PATH=%PATH%
  - python --version
  - pip --version
  - pip install -r requirements-ci.txt
  - pip install .
  # This will report setuptools and wheel
  - pip freeze --all

test_script:
  - ksconf --version
  - coverage run -m unittest discover -s tests

after_test:
  - codecov
  - coveralls

cache:
  - '%LOCALAPPDATA%\pip\cache'
