#!/bin/bash
version=$(git describe --tags --always)
version=${version/v/}
test -d build || mkdir build
zipapp=build/ksconf-zipapp-${version}.py.zip
standalone=build/ksconf-${version}-standalone

test -f ksconf/_version.py || python setup.py build

echo "Building stanadalone zipapp for $version"

cat > __main__.py <<HERE
from ksconf.cli import cli
cli()
HERE

rm -f $zipapp 2>/dev/null
zip $zipapp __main__.py $(find ksconf -name '*.py')
rm -f __main__.py

echo "Build zip file $zipapp --> $standalone"
( echo '#!/usr/bin/env python'; cat $zipapp; ) > ${standalone}

echo "done"
