#!/bin/bash
set -e
VENV=venv_docs

python setup.py >/dev/null 2>&1 || true

if [[ ! -d "$VENV" ]]
then
    python3 -m virtualenv "$VENV"
    "$VENV/bin/pip" install -r requirements-doc.txt sphinx_rtd_theme
fi
. "$VENV"/bin/activate

python make_dyn_docs.py || true


# Or, something like:   make html
sphinx-autobuild -p 9999 -b html -z ksconf docs/source docs/build/html -B
