#!/bin/bash
version=$(git describe --tags --always)
version=${version/v/}
test -d build || mkdir build
zipapp=dist/ksconf-${version}
install_temp=build/ksconf-$version
test -d $install_temp && rm -rf $install_temp

if python -c "import sys; sys.exit(sys.version_info>(3,5))"; then
    echo "Need python 3.5 or great to run this script."
    echo "Consider running with PYENV_VERSION=3.6.5"
    exit
fi

echo "Building stanadalone zipapp for $version"

pip install . --target=$install_temp --no-compile

# Python must be 3.5 or greater

python -m zipapp $install_temp --output ${zipapp}.pyz --python '/usr/bin/env python' --main ksconf.cli:cli
python -m zipapp ${zipapp}.pyz --output ${zipapp}-splunk.pyz --python '/opt/splunk/bin/python'

echo "done"
